name: meetkoch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.3
  intl: ^0.17.0  
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0

flutter_icons:
  image_path: "assets/icons/MeetKoch (1).png"
  android: true
  ios: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/MeetKoch Icons.png
    - assets/icons/MeetKoch (1).png
    - assets/icons/MeetKoch (2).png
    - assets/icons/default.png
    
    