// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq23_Nju_OHPX6RSfwIgSsuxWTRCVWv20',
    appId: '1:28049729949:web:ed47f745a23f83e1196774',
    messagingSenderId: '28049729949',
    projectId: 'meetkoch-b248e',
    authDomain: 'meetkoch-b248e.firebaseapp.com',
    storageBucket: 'meetkoch-b248e.appspot.com',
    measurementId: 'G-R22MB1Y8D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRMWDoSgRo4JKtH1E49xLvHEei8SpBe6Y',
    appId: '1:28049729949:android:292057244b8331b0196774',
    messagingSenderId: '28049729949',
    projectId: 'meetkoch-b248e',
    storageBucket: 'meetkoch-b248e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtCmkjvGNVPE8FXj5B3PnDDveK6U7rWA',
    appId: '1:28049729949:ios:af0c15dc49e9d36c196774',
    messagingSenderId: '28049729949',
    projectId: 'meetkoch-b248e',
    storageBucket: 'meetkoch-b248e.appspot.com',
    iosBundleId: 'com.example.meetkoch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEtCmkjvGNVPE8FXj5B3PnDDveK6U7rWA',
    appId: '1:28049729949:ios:af0c15dc49e9d36c196774',
    messagingSenderId: '28049729949',
    projectId: 'meetkoch-b248e',
    storageBucket: 'meetkoch-b248e.appspot.com',
    iosBundleId: 'com.example.meetkoch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq23_Nju_OHPX6RSfwIgSsuxWTRCVWv20',
    appId: '1:28049729949:web:9bcd3ce0ef3cb5a9196774',
    messagingSenderId: '28049729949',
    projectId: 'meetkoch-b248e',
    authDomain: 'meetkoch-b248e.firebaseapp.com',
    storageBucket: 'meetkoch-b248e.appspot.com',
    measurementId: 'G-DQHX5E4QLC',
  );
}
